//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.05 at 05:29:53 PM ART 
//


package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.entities.consultaempresagenerica1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Empresa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Empresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DOCUMENTO" type="{}DOCUMENTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Empresa", propOrder = {
    "razonsocial1",
    "razonsocial2",
    "ic",
    "documento"
})
public class Empresa {

    @XmlElement(name = "RAZONSOCIAL1", required = true)
    protected String razonsocial1;
    @XmlElement(name = "RAZONSOCIAL2", required = true)
    protected String razonsocial2;
    @XmlElement(name = "IC", required = true)
    protected BigDecimal ic;
    @XmlElement(name = "DOCUMENTO", required = true)
    protected DOCUMENTO documento;

    /**
     * Gets the value of the razonsocial1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRAZONSOCIAL1() {
        return razonsocial1;
    }

    /**
     * Sets the value of the razonsocial1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAZONSOCIAL1(String value) {
        this.razonsocial1 = value;
    }

    /**
     * Gets the value of the razonsocial2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRAZONSOCIAL2() {
        return razonsocial2;
    }

    /**
     * Sets the value of the razonsocial2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAZONSOCIAL2(String value) {
        this.razonsocial2 = value;
    }

    /**
     * Gets the value of the ic property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIC() {
        return ic;
    }

    /**
     * Sets the value of the ic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIC(BigDecimal value) {
        this.ic = value;
    }

    /**
     * Gets the value of the documento property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTO }
     *     
     */
    public DOCUMENTO getDOCUMENTO() {
        return documento;
    }

    /**
     * Sets the value of the documento property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTO }
     *     
     */
    public void setDOCUMENTO(DOCUMENTO value) {
        this.documento = value;
    }

}
