//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.05 at 05:29:54 PM ART 
//


package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.entities.consultasociosparticular1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contratos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contratos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datosInterlocutor" type="{}datosInterlocutor"/>
 *         &lt;element name="listaContratos" type="{}listaContratos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contratos", propOrder = {
    "datosInterlocutor",
    "listaContratos"
})
@XmlRootElement
public class Contratos {

    @XmlElement(required = true)
    protected DatosInterlocutor datosInterlocutor;
    @XmlElement(required = true)
    protected ListaContratos listaContratos;

    /**
     * Gets the value of the datosInterlocutor property.
     * 
     * @return
     *     possible object is
     *     {@link DatosInterlocutor }
     *     
     */
    public DatosInterlocutor getDatosInterlocutor() {
        return datosInterlocutor;
    }

    /**
     * Sets the value of the datosInterlocutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosInterlocutor }
     *     
     */
    public void setDatosInterlocutor(DatosInterlocutor value) {
        this.datosInterlocutor = value;
    }

    /**
     * Gets the value of the listaContratos property.
     * 
     * @return
     *     possible object is
     *     {@link ListaContratos }
     *     
     */
    public ListaContratos getListaContratos() {
        return listaContratos;
    }

    /**
     * Sets the value of the listaContratos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaContratos }
     *     
     */
    public void setListaContratos(ListaContratos value) {
        this.listaContratos = value;
    }

}
