package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 26 15:35:16 ART 2014
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://osde.com.ar/services/responsablepagoservice", name = "ResponsableDePagoService")
//@XmlSeeAlso({ar.com.osde.entities.socio.responsabledepago.filters.ObjectFactory.class, ar.com.osde.entities.socio.responsabledepago.ObjectFactory.class, ar.com.osde.entities.common.unidadesfacturacion.ObjectFactory.class, ar.com.osde.entities.plan.ObjectFactory.class, ObjectFactory.class})
public interface ResponsableDePagoService {

//    @WebResult(name = "ResponsableDePagoConPlanServicio", targetNamespace = "")
//    @RequestWrapper(localName = "searchResponsableDePagoConPlanServicioHistorico", targetNamespace = "http://osde.com.ar/services/responsablepagoservice", className = "ar.com.osde.services.responsablepagoservice.SearchResponsableDePagoConPlanServicioHistorico")
//    @WebMethod
//    @ResponseWrapper(localName = "searchResponsableDePagoConPlanServicioHistoricoResponse", targetNamespace = "http://osde.com.ar/services/responsablepagoservice", className = "ar.com.osde.services.responsablepagoservice.SearchResponsableDePagoConPlanServicioHistoricoResponse")
//    public ar.com.osde.services.responsablepagoservice.SearchResult searchResponsableDePagoConPlanServicioHistorico(
//        @WebParam(name = "filter", targetNamespace = "http://osde.com.ar/services/responsablepagoservice")
//        ar.com.osde.entities.socio.responsabledepago.filters.ResponsableDePagoHistorialFilter filter
//    ) throws ResponsableDePagoNoRegistradoException_Exception;
//
//    @WebResult(name = "ResponsableDePagoConPlanServicio", targetNamespace = "")
//    @RequestWrapper(localName = "searchResponsableDePagoConPlanServicio", targetNamespace = "http://osde.com.ar/services/responsablepagoservice", className = "ar.com.osde.services.responsablepagoservice.SearchResponsableDePagoConPlanServicio")
//    @WebMethod
//    @ResponseWrapper(localName = "searchResponsableDePagoConPlanServicioResponse", targetNamespace = "http://osde.com.ar/services/responsablepagoservice", className = "ar.com.osde.services.responsablepagoservice.SearchResponsableDePagoConPlanServicioResponse")
//    public ar.com.osde.services.responsablepagoservice.SearchResult searchResponsableDePagoConPlanServicio(
//        @WebParam(name = "filter", targetNamespace = "http://osde.com.ar/services/responsablepagoservice")
//        ar.com.osde.entities.socio.responsabledepago.filters.ResponsableDePagoFilter filter
//    ) throws ResponsableDePagoNoRegistradoException_Exception;
}
