
/*
 * 
 */

package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 26 15:35:16 ART 2014
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "ResponsableDePagoServiceService", 
                  wsdlLocation = "http://testesb.osde.ar/services/ResponsableDePagoService?wsdl",
                  targetNamespace = "http://osde.com.ar/services/responsablepagoservice") 
public class ResponsableDePagoServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://osde.com.ar/services/responsablepagoservice", "ResponsableDePagoServiceService");
    public final static QName ResponsableDePagoServicePort = new QName("http://osde.com.ar/services/responsablepagoservice", "ResponsableDePagoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://testesb.osde.ar/services/ResponsableDePagoService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://testesb.osde.ar/services/ResponsableDePagoService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ResponsableDePagoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResponsableDePagoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponsableDePagoServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ResponsableDePagoService
     */
    @WebEndpoint(name = "ResponsableDePagoServicePort")
    public ResponsableDePagoService getResponsableDePagoServicePort() {
        return super.getPort(ResponsableDePagoServicePort, ResponsableDePagoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResponsableDePagoService
     */
    @WebEndpoint(name = "ResponsableDePagoServicePort")
    public ResponsableDePagoService getResponsableDePagoServicePort(WebServiceFeature... features) {
        return super.getPort(ResponsableDePagoServicePort, ResponsableDePagoService.class, features);
    }

}
