package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.entities.consultaempresagenerica2;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.02.13 at 11:12:28 AM ART 
//


import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
* <p>Java class for Empresa complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="Empresa">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="IC_UF" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
*         &lt;element name="UNIDADFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="DOCUMENTO" type="{}DOCUMENTO"/>
*         &lt;element name="FECALT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
*         &lt;element name="FECBAJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="DESCRIP_LONG" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="DOMICILIO" type="{}DOMICILIO"/>
*         &lt;element name="DESC_TIPEMP" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Empresa", propOrder = {
 "razonsocial1",
 "razonsocial2",
 "icuf",
 "unidadfact",
 "documento",
 "fecalt",
 "fecbaj",
 "descriplong",
 "domicilio",
 "desctipemp"
})
public class Empresa {

 @XmlElement(name = "RAZONSOCIAL1", required = true)
 protected String razonsocial1;
 @XmlElement(name = "RAZONSOCIAL2", required = true)
 protected String razonsocial2;
 @XmlElement(name = "IC_UF", required = true)
 protected BigDecimal icuf;
 @XmlElement(name = "UNIDADFACT", required = true)
 protected String unidadfact;
 @XmlElement(name = "DOCUMENTO", required = true)
 protected DOCUMENTO documento;
 @XmlElement(name = "FECALT", required = true)
 @XmlSchemaType(name = "dateTime")
 protected XMLGregorianCalendar fecalt;
 @XmlElement(name = "FECBAJ", required = true)
 protected String fecbaj;
 @XmlElement(name = "DESCRIP_LONG", required = true)
 protected String descriplong;
 @XmlElement(name = "DOMICILIO", required = true)
 protected DOMICILIO domicilio;
 @XmlElement(name = "DESC_TIPEMP", required = true)
 protected String desctipemp;

 /**
  * Gets the value of the razonsocial1 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getRAZONSOCIAL1() {
     return razonsocial1;
 }

 /**
  * Sets the value of the razonsocial1 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setRAZONSOCIAL1(String value) {
     this.razonsocial1 = value;
 }

 /**
  * Gets the value of the razonsocial2 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getRAZONSOCIAL2() {
     return razonsocial2;
 }

 /**
  * Sets the value of the razonsocial2 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setRAZONSOCIAL2(String value) {
     this.razonsocial2 = value;
 }

 /**
  * Gets the value of the icuf property.
  * 
  * @return
  *     possible object is
  *     {@link BigDecimal }
  *     
  */
 public BigDecimal getICUF() {
     return icuf;
 }

 /**
  * Sets the value of the icuf property.
  * 
  * @param value
  *     allowed object is
  *     {@link BigDecimal }
  *     
  */
 public void setICUF(BigDecimal value) {
     this.icuf = value;
 }

 /**
  * Gets the value of the unidadfact property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getUNIDADFACT() {
     return unidadfact;
 }

 /**
  * Sets the value of the unidadfact property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setUNIDADFACT(String value) {
     this.unidadfact = value;
 }

 /**
  * Gets the value of the documento property.
  * 
  * @return
  *     possible object is
  *     {@link DOCUMENTO }
  *     
  */
 public DOCUMENTO getDOCUMENTO() {
     return documento;
 }

 /**
  * Sets the value of the documento property.
  * 
  * @param value
  *     allowed object is
  *     {@link DOCUMENTO }
  *     
  */
 public void setDOCUMENTO(DOCUMENTO value) {
     this.documento = value;
 }

 /**
  * Gets the value of the fecalt property.
  * 
  * @return
  *     possible object is
  *     {@link XMLGregorianCalendar }
  *     
  */
 public XMLGregorianCalendar getFECALT() {
     return fecalt;
 }

 /**
  * Sets the value of the fecalt property.
  * 
  * @param value
  *     allowed object is
  *     {@link XMLGregorianCalendar }
  *     
  */
 public void setFECALT(XMLGregorianCalendar value) {
     this.fecalt = value;
 }

 /**
  * Gets the value of the fecbaj property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getFECBAJ() {
     return fecbaj;
 }

 /**
  * Sets the value of the fecbaj property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setFECBAJ(String value) {
     this.fecbaj = value;
 }

 /**
  * Gets the value of the descriplong property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getDESCRIPLONG() {
     return descriplong;
 }

 /**
  * Sets the value of the descriplong property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setDESCRIPLONG(String value) {
     this.descriplong = value;
 }

 /**
  * Gets the value of the domicilio property.
  * 
  * @return
  *     possible object is
  *     {@link DOMICILIO }
  *     
  */
 public DOMICILIO getDOMICILIO() {
     return domicilio;
 }

 /**
  * Sets the value of the domicilio property.
  * 
  * @param value
  *     allowed object is
  *     {@link DOMICILIO }
  *     
  */
 public void setDOMICILIO(DOMICILIO value) {
     this.domicilio = value;
 }

 /**
  * Gets the value of the desctipemp property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getDESCTIPEMP() {
     return desctipemp;
 }

 /**
  * Sets the value of the desctipemp property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setDESCTIPEMP(String value) {
     this.desctipemp = value;
 }

}
