//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.06 at 02:37:10 PM ART 
//


package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.entities.consultaempresagenerica2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="empresas">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Empresa" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="IC_UF" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="UNIDADFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DOCUMENTO">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="TIPDOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="NRODOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="FECALT" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="FECBAJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DESCRIP_LONG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DOMICILIO">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="CALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="NRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="PISO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="DPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="CODPOSTAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="CODPROVINCIA" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="PROVINCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="DESC_TIPEMP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fault">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="faultcode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="faultstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="faultactor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body",
    "fault"
})
@XmlRootElement(name = "envelope")
public class Envelope {

    @XmlElement(required = true)
    protected Envelope.Header header;
    @XmlElement(required = true)
    protected Envelope.Body body;
    @XmlElement(required = true)
    protected Envelope.Fault fault;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Envelope.Header }
     *     
     */
    public Envelope.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope.Header }
     *     
     */
    public void setHeader(Envelope.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Envelope.Body }
     *     
     */
    public Envelope.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope.Body }
     *     
     */
    public void setBody(Envelope.Body value) {
        this.body = value;
    }

    /**
     * Gets the value of the fault property.
     * 
     * @return
     *     possible object is
     *     {@link Envelope.Fault }
     *     
     */
    public Envelope.Fault getFault() {
        return fault;
    }

    /**
     * Sets the value of the fault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope.Fault }
     *     
     */
    public void setFault(Envelope.Fault value) {
        this.fault = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="empresas">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Empresa" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="IC_UF" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="UNIDADFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DOCUMENTO">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="TIPDOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="NRODOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="FECALT" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="FECBAJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DESCRIP_LONG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DOMICILIO">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="CALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="NRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="PISO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="DPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="CODPOSTAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                       &lt;element name="CODPROVINCIA" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="PROVINCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="DESC_TIPEMP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "empresas"
    })
    public static class Body {

        @XmlElement(required = true)
        protected Envelope.Body.Empresas empresas;

        /**
         * Gets the value of the empresas property.
         * 
         * @return
         *     possible object is
         *     {@link Envelope.Body.Empresas }
         *     
         */
        public Envelope.Body.Empresas getEmpresas() {
            return empresas;
        }

        /**
         * Sets the value of the empresas property.
         * 
         * @param value
         *     allowed object is
         *     {@link Envelope.Body.Empresas }
         *     
         */
        public void setEmpresas(Envelope.Body.Empresas value) {
            this.empresas = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Empresa" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IC_UF" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="UNIDADFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DOCUMENTO">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="TIPDOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="NRODOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="FECALT" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="FECBAJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DESCRIP_LONG" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DOMICILIO">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="CALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="NRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="PISO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="DPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="CODPOSTAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                             &lt;element name="CODPROVINCIA" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="PROVINCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="DESC_TIPEMP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "empresa"
        })
        public static class Empresas {

            @XmlElement(name = "Empresa")
            protected List<Envelope.Body.Empresas.Empresa> empresa;

            /**
             * Gets the value of the empresa property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the empresa property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEmpresa().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Envelope.Body.Empresas.Empresa }
             * 
             * 
             */
            public List<Envelope.Body.Empresas.Empresa> getEmpresa() {
                if (empresa == null) {
                    empresa = new ArrayList<Envelope.Body.Empresas.Empresa>();
                }
                return this.empresa;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RAZONSOCIAL1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RAZONSOCIAL2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IC_UF" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="UNIDADFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DOCUMENTO">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="TIPDOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="NRODOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="FECALT" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="FECBAJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DESCRIP_LONG" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DOMICILIO">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="CALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="NRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="PISO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="DPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="CODPOSTAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                   &lt;element name="CODPROVINCIA" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="PROVINCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="DESC_TIPEMP" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "razonsocial1",
                "razonsocial2",
                "icuf",
                "unidadfact",
                "documento",
                "fecalt",
                "fecbaj",
                "descriplong",
                "domicilio",
                "desctipemp"
            })
            public static class Empresa {

                @XmlElement(name = "RAZONSOCIAL1", required = true)
                protected String razonsocial1;
                @XmlElement(name = "RAZONSOCIAL2", required = true)
                protected String razonsocial2;
                @XmlElement(name = "IC_UF")
                protected long icuf;
                @XmlElement(name = "UNIDADFACT", required = true)
                protected String unidadfact;
                @XmlElement(name = "DOCUMENTO", required = true)
                protected Envelope.Body.Empresas.Empresa.DOCUMENTO documento;
                @XmlElement(name = "FECALT", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar fecalt;
                @XmlElement(name = "FECBAJ", required = true)
                protected String fecbaj;
                @XmlElement(name = "DESCRIP_LONG", required = true)
                protected String descriplong;
                @XmlElement(name = "DOMICILIO", required = true)
                protected Envelope.Body.Empresas.Empresa.DOMICILIO domicilio;
                @XmlElement(name = "DESC_TIPEMP", required = true)
                protected String desctipemp;

                /**
                 * Gets the value of the razonsocial1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRAZONSOCIAL1() {
                    return razonsocial1;
                }

                /**
                 * Sets the value of the razonsocial1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRAZONSOCIAL1(String value) {
                    this.razonsocial1 = value;
                }

                /**
                 * Gets the value of the razonsocial2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRAZONSOCIAL2() {
                    return razonsocial2;
                }

                /**
                 * Sets the value of the razonsocial2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRAZONSOCIAL2(String value) {
                    this.razonsocial2 = value;
                }

                /**
                 * Gets the value of the icuf property.
                 * 
                 */
                public long getICUF() {
                    return icuf;
                }

                /**
                 * Sets the value of the icuf property.
                 * 
                 */
                public void setICUF(long value) {
                    this.icuf = value;
                }

                /**
                 * Gets the value of the unidadfact property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUNIDADFACT() {
                    return unidadfact;
                }

                /**
                 * Sets the value of the unidadfact property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUNIDADFACT(String value) {
                    this.unidadfact = value;
                }

                /**
                 * Gets the value of the documento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Envelope.Body.Empresas.Empresa.DOCUMENTO }
                 *     
                 */
                public Envelope.Body.Empresas.Empresa.DOCUMENTO getDOCUMENTO() {
                    return documento;
                }

                /**
                 * Sets the value of the documento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Envelope.Body.Empresas.Empresa.DOCUMENTO }
                 *     
                 */
                public void setDOCUMENTO(Envelope.Body.Empresas.Empresa.DOCUMENTO value) {
                    this.documento = value;
                }

                /**
                 * Gets the value of the fecalt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFECALT() {
                    return fecalt;
                }

                /**
                 * Sets the value of the fecalt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFECALT(XMLGregorianCalendar value) {
                    this.fecalt = value;
                }

                /**
                 * Gets the value of the fecbaj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFECBAJ() {
                    return fecbaj;
                }

                /**
                 * Sets the value of the fecbaj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFECBAJ(String value) {
                    this.fecbaj = value;
                }

                /**
                 * Gets the value of the descriplong property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCRIPLONG() {
                    return descriplong;
                }

                /**
                 * Sets the value of the descriplong property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCRIPLONG(String value) {
                    this.descriplong = value;
                }

                /**
                 * Gets the value of the domicilio property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Envelope.Body.Empresas.Empresa.DOMICILIO }
                 *     
                 */
                public Envelope.Body.Empresas.Empresa.DOMICILIO getDOMICILIO() {
                    return domicilio;
                }

                /**
                 * Sets the value of the domicilio property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Envelope.Body.Empresas.Empresa.DOMICILIO }
                 *     
                 */
                public void setDOMICILIO(Envelope.Body.Empresas.Empresa.DOMICILIO value) {
                    this.domicilio = value;
                }

                /**
                 * Gets the value of the desctipemp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCTIPEMP() {
                    return desctipemp;
                }

                /**
                 * Sets the value of the desctipemp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCTIPEMP(String value) {
                    this.desctipemp = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="TIPDOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="NRODOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "tipdoc",
                    "nrodoc"
                })
                public static class DOCUMENTO {

                    @XmlElement(name = "TIPDOC", required = true)
                    protected String tipdoc;
                    @XmlElement(name = "NRODOC")
                    protected long nrodoc;

                    /**
                     * Gets the value of the tipdoc property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTIPDOC() {
                        return tipdoc;
                    }

                    /**
                     * Sets the value of the tipdoc property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTIPDOC(String value) {
                        this.tipdoc = value;
                    }

                    /**
                     * Gets the value of the nrodoc property.
                     * 
                     */
                    public long getNRODOC() {
                        return nrodoc;
                    }

                    /**
                     * Sets the value of the nrodoc property.
                     * 
                     */
                    public void setNRODOC(long value) {
                        this.nrodoc = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="CALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="NRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="PISO" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="DPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="CODPOSTAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *         &lt;element name="CODPROVINCIA" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="PROVINCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "calle",
                    "nro",
                    "piso",
                    "dpto",
                    "localidad",
                    "codpostal",
                    "codprovincia",
                    "provincia"
                })
                public static class DOMICILIO {

                    @XmlElement(name = "CALLE", required = true)
                    protected String calle;
                    @XmlElement(name = "NRO", required = true)
                    protected String nro;
                    @XmlElement(name = "PISO", required = true)
                    protected String piso;
                    @XmlElement(name = "DPTO", required = true)
                    protected String dpto;
                    @XmlElement(name = "LOCALIDAD", required = true)
                    protected String localidad;
                    @XmlElement(name = "CODPOSTAL")
                    protected short codpostal;
                    @XmlElement(name = "CODPROVINCIA")
                    protected byte codprovincia;
                    @XmlElement(name = "PROVINCIA", required = true)
                    protected String provincia;

                    /**
                     * Gets the value of the calle property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCALLE() {
                        return calle;
                    }

                    /**
                     * Sets the value of the calle property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCALLE(String value) {
                        this.calle = value;
                    }

                    /**
                     * Gets the value of the nro property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNRO() {
                        return nro;
                    }

                    /**
                     * Sets the value of the nro property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNRO(String value) {
                        this.nro = value;
                    }

                    /**
                     * Gets the value of the piso property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPISO() {
                        return piso;
                    }

                    /**
                     * Sets the value of the piso property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPISO(String value) {
                        this.piso = value;
                    }

                    /**
                     * Gets the value of the dpto property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDPTO() {
                        return dpto;
                    }

                    /**
                     * Sets the value of the dpto property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDPTO(String value) {
                        this.dpto = value;
                    }

                    /**
                     * Gets the value of the localidad property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getLOCALIDAD() {
                        return localidad;
                    }

                    /**
                     * Sets the value of the localidad property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setLOCALIDAD(String value) {
                        this.localidad = value;
                    }

                    /**
                     * Gets the value of the codpostal property.
                     * 
                     */
                    public short getCODPOSTAL() {
                        return codpostal;
                    }

                    /**
                     * Sets the value of the codpostal property.
                     * 
                     */
                    public void setCODPOSTAL(short value) {
                        this.codpostal = value;
                    }

                    /**
                     * Gets the value of the codprovincia property.
                     * 
                     */
                    public byte getCODPROVINCIA() {
                        return codprovincia;
                    }

                    /**
                     * Sets the value of the codprovincia property.
                     * 
                     */
                    public void setCODPROVINCIA(byte value) {
                        this.codprovincia = value;
                    }

                    /**
                     * Gets the value of the provincia property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPROVINCIA() {
                        return provincia;
                    }

                    /**
                     * Sets the value of the provincia property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPROVINCIA(String value) {
                        this.provincia = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="faultcode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="faultstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="faultactor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "faultcode",
        "faultstring",
        "faultactor"
    })
    public static class Fault {

        protected short faultcode;
        @XmlElement(required = true)
        protected String faultstring;
        @XmlElement(required = true)
        protected String faultactor;

        /**
         * Gets the value of the faultcode property.
         * 
         */
        public short getFaultcode() {
            return faultcode;
        }

        /**
         * Sets the value of the faultcode property.
         * 
         */
        public void setFaultcode(short value) {
            this.faultcode = value;
        }

        /**
         * Gets the value of the faultstring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFaultstring() {
            return faultstring;
        }

        /**
         * Sets the value of the faultstring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFaultstring(String value) {
            this.faultstring = value;
        }

        /**
         * Gets the value of the faultactor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFaultactor() {
            return faultactor;
        }

        /**
         * Sets the value of the faultactor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFaultactor(String value) {
            this.faultactor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String message;

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

    }

}
