//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.06 at 02:37:10 PM ART 
//


package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.entities.consultaempresagenerica2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.com.osde.entities.consultaempresasgenerica2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.com.osde.entities.consultaempresasgenerica2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Envelope.Body.Empresas.Empresa }
     * 
     */
    public Envelope.Body.Empresas.Empresa createEnvelopeBodyEmpresasEmpresa() {
        return new Envelope.Body.Empresas.Empresa();
    }

    /**
     * Create an instance of {@link Envelope.Header }
     * 
     */
    public Envelope.Header createEnvelopeHeader() {
        return new Envelope.Header();
    }

    /**
     * Create an instance of {@link Envelope.Body.Empresas.Empresa.DOCUMENTO }
     * 
     */
    public Envelope.Body.Empresas.Empresa.DOCUMENTO createEnvelopeBodyEmpresasEmpresaDOCUMENTO() {
        return new Envelope.Body.Empresas.Empresa.DOCUMENTO();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link Envelope.Body }
     * 
     */
    public Envelope.Body createEnvelopeBody() {
        return new Envelope.Body();
    }

    /**
     * Create an instance of {@link Envelope.Body.Empresas }
     * 
     */
    public Envelope.Body.Empresas createEnvelopeBodyEmpresas() {
        return new Envelope.Body.Empresas();
    }

    /**
     * Create an instance of {@link Envelope.Body.Empresas.Empresa.DOMICILIO }
     * 
     */
    public Envelope.Body.Empresas.Empresa.DOMICILIO createEnvelopeBodyEmpresasEmpresaDOMICILIO() {
        return new Envelope.Body.Empresas.Empresa.DOMICILIO();
    }

    /**
     * Create an instance of {@link Envelope.Fault }
     * 
     */
    public Envelope.Fault createEnvelopeFault() {
        return new Envelope.Fault();
    }

}
