
package ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 26 15:35:16 ART 2014
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ResponsableDePagoNoRegistradoException", targetNamespace = "http://osde.com.ar/services/responsablepagoservice")
public class ResponsableDePagoNoRegistradoException_Exception extends Exception {
    public static final long serialVersionUID = 20140826153516L;
    
    private ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice.ResponsableDePagoNoRegistradoException responsableDePagoNoRegistradoException;

    public ResponsableDePagoNoRegistradoException_Exception() {
        super();
    }
    
    public ResponsableDePagoNoRegistradoException_Exception(String message) {
        super(message);
    }
    
    public ResponsableDePagoNoRegistradoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResponsableDePagoNoRegistradoException_Exception(String message, ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice.ResponsableDePagoNoRegistradoException responsableDePagoNoRegistradoException) {
        super(message);
        this.responsableDePagoNoRegistradoException = responsableDePagoNoRegistradoException;
    }

    public ResponsableDePagoNoRegistradoException_Exception(String message, ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice.ResponsableDePagoNoRegistradoException responsableDePagoNoRegistradoException, Throwable cause) {
        super(message, cause);
        this.responsableDePagoNoRegistradoException = responsableDePagoNoRegistradoException;
    }

    public ar.com.osde.fsw.tecnologia.validacionidentidad.SWYValidacionIdentidad.services.responsablepagoservice.ResponsableDePagoNoRegistradoException getFaultInfo() {
        return this.responsableDePagoNoRegistradoException;
    }
}
